### ISSUE TITLE
Steam doesn't open

### ISSUE THREAD

**Issue by ktmtvv** [Whisky-App/whisky-book#122]
steamwebhelper (a critical Steam component) is not responding. The Steam interface will be
unavailable. Find out more here.
- Restart Steam
• Restart Steam with hardware acceleration disabled
• Restart Steam with browser sandbox disabled
• Restart steamwebhelper
• Quit Steam

 What to do?

![Image](https://github.com/user-attachments/assets/c523df7b-495f-43ed-ad44-10272678e1c3)

**Comment by JoshuaBrest** [comment]
1. This isn't the place to report this issue.
2. This can be caused by many things. Do you have an antivirus installed? Did you modify wine?

**Comment by ktmtvv** [comment]
> 1. This isn't the place to report this issue.
> 2. This can be caused by many things. Do you have an antivirus installed? Did you modify wine?

sorry for posting it here im kinda newbie... where should I ask this type of questions? 
actually, it used to work well before. then the app updated itself and it steam didn't open anymore

**Comment by mattmaniak** [comment]
Report this on the [Whisky App Issues page](https://github.com/Whisky-App/Whisky/issues) with an exact description and reproduction steps of the issue.
