### ISSUE TITLE
Whisky 2.3.3 steam installation issue with macbook air M3 13'

### ISSUE THREAD

**Issue by roux75** [Whisky-App/whisky-book#124]
When Whisky start to install Steam, the updater runs well and a steam message appears : steamwebhelper is no responding
![Image](https://github.com/user-attachments/assets/c9273e8a-8e9e-4191-a655-1f13befd85c4)

Is Whisky unable running steam ??

**Comment by mattmaniak** [comment]
Report this on the [Whisky App Issues page](https://github.com/Whisky-App/Whisky/issues) with an exact description and reproduction steps of the issue.
