### ISSUE TITLE
Whisky-loop steam no workin...

### ISSUE THREAD

**Issue by hasuwini77** [Whisky-App/whisky-book#76]
First of all I installed whisky successfully followed the instructions and managed to launch steam, then I downloaded a game ( CS ) to see if it works.

It was working ( didn't play it through but saw the menu at least), then I did quit the game, then quit Whisky and now when I launch it again, it simply won't work... the steam won't open...

I saw the icon kind of launching and then gone... 

Note that I've followed the comment here -> https://github.com/Whisky-App/Whisky/issues/788 

Tried to uninstall Whisky + steam using CleanmyMac an app Cleaner tried the installation again of whisky + steam but nothing, it won't launch

I'm ending up in a loop and honestly don't get it... 

Nothing will happen, any assist would be appreciated 

![Screenshot 2024-08-18 at 03 35 24](https://github.com/user-attachments/assets/e8c7fe77-c494-4064-ba61-111f4d15a46f)

**Comment by SheldonCoulson99** [comment]
I've had the same problem before, but it turned out it was just Steam taking too long to start up.
I suggest you wait a while (approx. 1 minute) after opening it to see if it starts up.

**Comment by hahayupgit** [comment]
First, you should make sure that all instances of Wine are killed by Whisky. You can do this by going to File -> Kill All Bottles. Also, Steam generally does take a while to open, and sometimes you may need to click on the icon a few times to get it to work.

Second, please add this issue under the main Whisky repository, as this repo is for the documentation only.

**Comment by West1e** [comment]
haveing the egsact problem can anyone help?
are there ay sulutions?
