### ISSUE TITLE
Risk of rain 2 does not load

### ISSUE THREAD

**Issue by Svemeh** [Whisky-App/whisky-book#82]
When opening risk of rain 2 through Whiskey it gets locked up on 3% on the initial loading screen

**Comment by mattmaniak** [comment]
Did you try to create a new bottle and installing the game again/reinstalling Whisky to ensure that it is not one-time issue?

**Comment by mattmaniak** [comment]
Please copy this issue to the [Whisky application repo](https://github.com/Whisky-App/Whisky/issues) as it has not much to do with the documentation. Optionally we will update the docs with the game status.
