### ISSUE TITLE
Command & Conquer Remastered Collection crashes after selection of C&C Version

### ISSUE THREAD

**Issue by ZockerVater** [Whisky-App/whisky-book#94]
![Bildschirmfoto 2024-09-21 um 19 51 42](https://github.com/user-attachments/assets/520d53d8-48d3-4fce-bd27-e4ac57e4640c)
![Bildschirmfoto 2024-09-21 um 19 52 03](https://github.com/user-attachments/assets/b6f54925-5e24-4a17-8737-348dba92725c)

Command & Conquer Remastered Collection crashes after selection of C&C Version is crashing after the selection screen. Dump file is never created, even if the game tries to create one.

Using Whisky 2.3.3 (41), latest Steam Version for Windows in a Win10 Bottle.

**Comment by ZockerVater** [comment]
Hi Mattmaniak,
I tried in three times now. Every time I created a new bottle, installed Steam and within the Steam Client I installed C&C.
So I can assure you it is not a one time issue.
I also tried it with different sync modes.

**Comment by mattmaniak** [comment]
I think that it will be more convenient to write this issue under the regular Whisky (app) repo. There are more issues like this there. Here we focus on docs.

**Comment by hahayupgit** [comment]
Agree, please open an issue in the main Whisky repo as this is a repo for the docs.
